spring:
  application:
    name: financial-portfolio-feed

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always